# Generated by Django 4.1.3 on 2022-11-16 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_image', models.ImageField(default='', upload_to='images')),
                ('user_gender', models.CharField(max_length=300)),
                ('user_location', models.TextField(max_length=300)),
                ('user_job_role', models.CharField(max_length=300)),
                ('user_bio', models.CharField(max_length=300)),
                ('user_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
